import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { AuthProvider } from "@/utils/AuthProvider";
import SideBar from "@/components/SideBar/SideBar";
import { QueryProvider } from "@/utils/QueryProvider";
import ToastProvider from "@/utils/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="backdrop-blur-sm flex ">
        <AuthProvider>
          <ToastProvider>
            <QueryProvider>
              <div className="flex gap-10 h-screen">
                <div>
                  <SideBar />
                </div>
                <div className="w-full mr-8 flex-1 overflow-y-auto">{children}</div>
              </div>
            </QueryProvider>
          </ToastProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
