import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const events = [
  {
    "name": "Event 1",
    "slug": "event-1",
    "recommend": false,
    "startDate": "2025-08-10T18:00:00.000Z",
    "startTime": "06:00 PM",
    "mainImage": "https://img.freepik.com/free-photo/japan-background-digital-art_23-2151546131.jpg",
    "venueAddress": "New York, NY",
    "venueNameFrontEnd": "Startup Hub",
    "venueNameBackEnd": "Investor Lounge",
    "city": "New York",
    "bali": false,
    "neighborhood": "Brooklyn",
    "lineUp": ["VC Investors", "Startup Founders"],
    "genres": ["Business", "Startup", "Investment"],
    "details": "A night for startups to pitch their ideas to investors.",
    "minAge": 21,
    "cost": 49.99,
    "promoterMail": "info@startupnight.com",
    "websiteUrl": "https://startupnight.com",
    "ticketLink": "https://startupnight.com/tickets",
    "videoLink": "https://youtube.com/startupnight",
    "recurring": "Monthly",
    "currency": "USD",
    "eventsMap": "https://example.com/map-startupnight",
    "catchVenues": ["Startup Hub"],
    "socialFbLink": "https://facebook.com/startupnight",
    "socialTwLink": "https://twitter.com/startupnight",
    "socialWtLink": "https://whatsapp.com/startupnight",
    "socialOtherLink": "https://linkedin.com/company/startupnight",
    "meta": "Join the biggest startup pitch event!",
    "venue": "Startup Hub",
    "guestlist": true
  },
  {
    "name": "Event 2",
    "slug": "event-2",
    "recommend": false,
    "startDate": "2025-09-15T18:00:00.000Z",
    "startTime": "06:00 PM",
    "mainImage": "https://img.freepik.com/free-photo/japan-background-digital-art_23-2151546131.jpg",
    "venueAddress": "New York, NY",
    "venueNameFrontEnd": "Startup Hub",
    "venueNameBackEnd": "Investor Lounge",
    "city": "New York",
    "bali": false,
    "neighborhood": "Brooklyn",
    "lineUp": ["VC Investors", "Startup Founders"],
    "genres": ["Business", "Startup", "Investment"],
    "details": "A night for startups to pitch their ideas to investors.",
    "minAge": 21,
    "cost": 49.99,
    "promoterMail": "info@startupnight.com",
    "websiteUrl": "https://startupnight.com",
    "ticketLink": "https://startupnight.com/tickets",
    "videoLink": "https://youtube.com/startupnight",
    "recurring": "Monthly",
    "currency": "USD",
    "eventsMap": "https://example.com/map-startupnight",
    "catchVenues": ["Startup Hub"],
    "socialFbLink": "https://facebook.com/startupnight",
    "socialTwLink": "https://twitter.com/startupnight",
    "socialWtLink": "https://whatsapp.com/startupnight",
    "socialOtherLink": "https://linkedin.com/company/startupnight",
    "meta": "Join the biggest startup pitch event!",
    "venue": "Startup Hub",
    "guestlist": true
  },
  {
    "name": "Event 3",
    "slug": "event-3",
    "recommend": false,
    "startDate": "2025-10-20T18:00:00.000Z",
    "startTime": "06:00 PM",
    "mainImage": "https://img.freepik.com/free-photo/japan-background-digital-art_23-2151546131.jpg",
    "venueAddress": "New York, NY",
    "venueNameFrontEnd": "Startup Hub",
    "venueNameBackEnd": "Investor Lounge",
    "city": "New York",
    "bali": false,
    "neighborhood": "Brooklyn",
    "lineUp": ["VC Investors", "Startup Founders"],
    "genres": ["Business", "Startup", "Investment"],
    "details": "A night for startups to pitch their ideas to investors.",
    "minAge": 21,
    "cost": 49.99,
    "promoterMail": "info@startupnight.com",
    "websiteUrl": "https://startupnight.com",
    "ticketLink": "https://startupnight.com/tickets",
    "videoLink": "https://youtube.com/startupnight",
    "recurring": "Monthly",
    "currency": "USD",
    "eventsMap": "https://example.com/map-startupnight",
    "catchVenues": ["Startup Hub"],
    "socialFbLink": "https://facebook.com/startupnight",
    "socialTwLink": "https://twitter.com/startupnight",
    "socialWtLink": "https://whatsapp.com/startupnight",
    "socialOtherLink": "https://linkedin.com/company/startupnight",
    "meta": "Join the biggest startup pitch event!",
    "venue": "Startup Hub",
    "guestlist": true
  },
  {
    "name": "Event 4",
    "slug": "event-4",
    "startDate": "2025-11-25T18:00:00.000Z",
    "guestlist": true,
    "startTime": "06:00 PM",
    "mainImage": "https://img.freepik.com/free-photo/japan-background-digital-art_23-2151546131.jpg",
    "venueAddress": "New York, NY",
    "venueNameFrontEnd": "Startup Hub",
    "venueNameBackEnd": "Investor Lounge",
    "city": "New York",
    "bali": false,
    "neighborhood": "Brooklyn",
    "lineUp": ["VC Investors", "Startup Founders"],
    "genres": ["Business", "Startup", "Investment"],
    "details": "A night for startups to pitch their ideas to investors.",
    "minAge": 21,
    "cost": 49.99,
    "promoterMail": "info@startupnight.com",
    "websiteUrl": "https://startupnight.com",
    "ticketLink": "https://startupnight.com/tickets",
    "videoLink": "https://youtube.com/startupnight",
    "recurring": "Monthly",
    "currency": "USD",
    "eventsMap": "https://example.com/map-startupnight",
    "catchVenues": ["Startup Hub"],
    "socialFbLink": "https://facebook.com/startupnight",
    "socialTwLink": "https://twitter.com/startupnight",
    "socialWtLink": "https://whatsapp.com/startupnight",
    "socialOtherLink": "https://linkedin.com/company/startupnight",
    "meta": "Join the biggest startup pitch event!",
    "venue": "Startup Hub",
    "recommend": false
  },
  {
    "name": "Event 5",
    "slug": "event-5",
    "startDate": "2025-12-30T18:00:00.000Z",
    "guestlist": true,
    "startTime": "06:00 PM",
    "mainImage": "https://img.freepik.com/free-photo/japan-background-digital-art_23-2151546131.jpg",
    "venueAddress": "New York, NY",
    "venueNameFrontEnd": "Startup Hub",
    "venueNameBackEnd": "Investor Lounge",
    "city": "New York",
    "bali": false,
    "neighborhood": "Brooklyn",
    "lineUp": ["VC Investors", "Startup Founders"],
    "genres": ["Business", "Startup", "Investment"],
    "details": "A night for startups to pitch their ideas to investors.",
    "minAge": 21,
    "cost": 49.99,
    "promoterMail": "info@startupnight.com",
    "websiteUrl": "https://startupnight.com",
    "ticketLink": "https://startupnight.com/tickets",
    "videoLink": "https://youtube.com/startupnight",
    "recurring": "Monthly",
    "currency": "USD",
    "eventsMap": "https://example.com/map-startupnight",
    "catchVenues": ["Startup Hub"],
    "socialFbLink": "https://facebook.com/startupnight",
    "socialTwLink": "https://twitter.com/startupnight",
    "socialWtLink": "https://whatsapp.com/startupnight",
    "socialOtherLink": "https://linkedin.com/company/startupnight",
    "meta": "Join the biggest startup pitch event!",
    "venue": "Startup Hub",
    "recommend": false
  },
  {
    "name": "Event 6",
    "slug": "event-6",
    "recommend": false,
    "startDate": "2025-07-05T19:00:00.000Z",
    "startTime": "07:00 PM",
    "mainImage": "https://img.freepik.com/free-photo/japan-background-digital-art_23-2151546131.jpg",
    "venueAddress": "San Francisco, CA",
    "venueNameFrontEnd": "Innovation Center",
    "venueNameBackEnd": "Main Hall",
    "city": "San Francisco",
    "bali": false,
    "neighborhood": "SoMa",
    "lineUp": ["Tech Leaders", "Founders"],
    "genres": ["Tech", "Networking"],
    "details": "A meetup for tech minds and entrepreneurs.",
    "minAge": 18,
    "cost": 29.99,
    "promoterMail": "info@techmeet.com",
    "websiteUrl": "https://techmeet.com",
    "ticketLink": "https://techmeet.com/tickets",
    "videoLink": "https://youtube.com/techmeet",
    "recurring": "Weekly",
    "currency": "USD",
    "eventsMap": "https://example.com/map-techmeet",
    "catchVenues": ["Innovation Center"],
    "socialFbLink": "https://facebook.com/techmeet",
    "socialTwLink": "https://twitter.com/techmeet",
    "socialWtLink": "https://whatsapp.com/techmeet",
    "socialOtherLink": "https://linkedin.com/company/techmeet",
    "meta": "Connect with fellow innovators!",
    "venue": "Innovation Center",
    "guestlist": false
  },
  {
    "name": "Event 7",
    "slug": "event-7",
    "recommend": false,
    "startDate": "2025-09-01T20:30:00.000Z",
    "startTime": "08:30 PM",
    "mainImage": "https://img.freepik.com/free-photo/japan-background-digital-art_23-2151546131.jpg",
    "venueAddress": "Los Angeles, CA",
    "venueNameFrontEnd": "Creative Loft",
    "venueNameBackEnd": "Penthouse",
    "city": "Los Angeles",
    "bali": false,
    "neighborhood": "Downtown",
    "lineUp": ["Designers", "Marketers"],
    "genres": ["Design", "Marketing"],
    "details": "Where creativity meets strategy.",
    "minAge": 21,
    "cost": 39.99,
    "promoterMail": "hello@creativeloft.com",
    "websiteUrl": "https://creativeloft.com",
    "ticketLink": "https://creativeloft.com/tickets",
    "videoLink": "https://youtube.com/creativeloft",
    "recurring": "Bi-Weekly",
    "currency": "USD",
    "eventsMap": "https://example.com/map-creativeloft",
    "catchVenues": ["Creative Loft"],
    "socialFbLink": "https://facebook.com/creativeloft",
    "socialTwLink": "https://twitter.com/creativeloft",
    "socialWtLink": "https://whatsapp.com/creativeloft",
    "socialOtherLink": "https://linkedin.com/company/creativeloft",
    "meta": "An exclusive creative networking night.",
    "venue": "Creative Loft",
    "guestlist": false
  },
  {
    "name": "Event 8",
    "slug": "event-8",
    "recommend": false,
    "startDate": "2025-10-15T17:00:00.000Z",
    "startTime": "05:00 PM",
    "mainImage": "https://img.freepik.com/free-photo/japan-background-digital-art_23-2151546131.jpg",
    "venueAddress": "Austin, TX",
    "venueNameFrontEnd": "Tech Garage",
    "venueNameBackEnd": "East Wing",
    "city": "Austin",
    "bali": false,
    "neighborhood": "Downtown",
    "lineUp": ["Engineers", "Startup Mentors"],
    "genres": ["Tech", "Coding"],
    "details": "Hands-on coding and collaboration.",
    "minAge": 18,
    "cost": 19.99,
    "promoterMail": "contact@techgarage.com",
    "websiteUrl": "https://techgarage.com",
    "ticketLink": "https://techgarage.com/tickets",
    "videoLink": "https://youtube.com/techgarage",
    "recurring": "Monthly",
    "currency": "USD",
    "eventsMap": "https://example.com/map-techgarage",
    "catchVenues": ["Tech Garage"],
    "socialFbLink": "https://facebook.com/techgarage",
    "socialTwLink": "https://twitter.com/techgarage",
    "socialWtLink": "https://whatsapp.com/techgarage",
    "socialOtherLink": "https://linkedin.com/company/techgarage",
    "meta": "Hack, code, and connect!",
    "venue": "Tech Garage",
    "guestlist": false
  },
  {
    "name": "Event 9",
    "slug": "event-9",
    "recommend": false,
    "startDate": "2025-11-11T19:30:00.000Z",
    "startTime": "07:30 PM",
    "mainImage": "https://img.freepik.com/free-photo/japan-background-digital-art_23-2151546131.jpg",
    "venueAddress": "Chicago, IL",
    "venueNameFrontEnd": "City Hall",
    "venueNameBackEnd": "Event Room A",
    "city": "Chicago",
    "bali": false,
    "neighborhood": "The Loop",
    "lineUp": ["Policy Makers", "Civic Tech"],
    "genres": ["Politics", "Tech", "Community"],
    "details": "Discussing the future of civic tech.",
    "minAge": 21,
    "cost": 0,
    "promoterMail": "events@cityhallchicago.com",
    "websiteUrl": "https://cityhallchicago.com",
    "ticketLink": "https://cityhallchicago.com/tickets",
    "videoLink": "https://youtube.com/cityhallchicago",
    "recurring": "Quarterly",
    "currency": "USD",
    "eventsMap": "https://example.com/map-cityhall",
    "catchVenues": ["City Hall"],
    "socialFbLink": "https://facebook.com/cityhallchicago",
    "socialTwLink": "https://twitter.com/cityhallchicago",
    "socialWtLink": "https://whatsapp.com/cityhallchicago",
    "socialOtherLink": "https://linkedin.com/company/cityhallchicago",
    "meta": "Connect on civic innovation!",
    "venue": "City Hall",
    "guestlist": false
  },
  {
    "name": "Event 10",
    "slug": "event-10",
    "recommend": false,
    "startDate": "2025-12-05T21:00:00.000Z",
    "startTime": "09:00 PM",
    "mainImage": "https://img.freepik.com/free-photo/japan-background-digital-art_23-2151546131.jpg",
    "venueAddress": "Seattle, WA",
    "venueNameFrontEnd": "Skyline Rooftop",
    "venueNameBackEnd": "Sky Lounge",
    "city": "Seattle",
    "bali": false,
    "neighborhood": "Capitol Hill",
    "lineUp": ["DJ Night", "Startup Showcase"],
    "genres": ["Music", "Tech", "Party"],
    "details": "Celebrate startups with music and lights!",
    "minAge": 21,
    "cost": 59.99,
    "promoterMail": "team@skylineevents.com",
    "websiteUrl": "https://skylineevents.com",
    "ticketLink": "https://skylineevents.com/tickets",
    "videoLink": "https://youtube.com/skylineevents",
    "recurring": "Once",
    "currency": "USD",
    "eventsMap": "https://example.com/map-skyline",
    "catchVenues": ["Skyline Rooftop"],
    "socialFbLink": "https://facebook.com/skylineevents",
    "socialTwLink": "https://twitter.com/skylineevents",
    "socialWtLink": "https://whatsapp.com/skylineevents",
    "socialOtherLink": "https://linkedin.com/company/skylineevents",
    "meta": "An unforgettable night of innovation and fun.",
    "venue": "Skyline Rooftop",
    "guestlist": false
  },

];







async function createDummyPosts() {

    

  try {
    // Generate 10 dummy posts
    

    const post = await prisma.event.createMany({
        data: events
      })

    console.log(`✅ Successfully added ${post} posts`);
  } catch (error) {
    console.error("❌ Error seeding data:", error.message);
  }
}

createDummyPosts();